import Head from 'next/head'
import News from '../Components/News'






export default function Home() {
  return (
    <div >
      <Head>
        <title>Early Bird News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bird.png" />
      </Head>



      <main >
        <News key='general' country='ph' category='general' />
      </main>


    </div>
  )
}
